export const hodlerAbi = [
    { type: 'constructor', inputs: [], stateMutability: 'nonpayable' },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'hodler',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'amount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'AddedVotes',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'previousAdmin',
          internalType: 'address',
          type: 'address',
          indexed: false,
        },
        {
          name: 'newAdmin',
          internalType: 'address',
          type: 'address',
          indexed: false,
        },
      ],
      name: 'AdminChanged',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'beacon',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
      ],
      name: 'BeaconUpgraded',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'controller',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'oldValue',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        {
          name: 'newValue',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'GovernanceDurationUpdated',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'tokenAddress',
          internalType: 'address',
          type: 'address',
          indexed: false,
        },
        {
          name: 'controller',
          internalType: 'address',
          type: 'address',
          indexed: false,
        },
        {
          name: 'lockSize',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        {
          name: 'lockDuration',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        {
          name: 'stakeDuration',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        {
          name: 'governanceDuration',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'HodlerInitialized',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        { name: 'version', internalType: 'uint8', type: 'uint8', indexed: false },
      ],
      name: 'Initialized',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'controller',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'oldValue',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        {
          name: 'newValue',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'LockDurationUpdated',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'controller',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'oldValue',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        {
          name: 'newValue',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'LockSizeUpdated',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'hodler',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'fingerprint',
          internalType: 'string',
          type: 'string',
          indexed: false,
        },
        {
          name: 'amount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        {
          name: 'operator',
          internalType: 'address',
          type: 'address',
          indexed: false,
        },
      ],
      name: 'Locked',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'account',
          internalType: 'address',
          type: 'address',
          indexed: false,
        },
      ],
      name: 'Paused',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'hodler',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'amount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'RemovedVotes',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'hodler',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'amount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        { name: 'redeemed', internalType: 'bool', type: 'bool', indexed: false },
        {
          name: 'relayRewardAmount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        {
          name: 'stakingRewardAmount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'Rewarded',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        { name: 'role', internalType: 'bytes32', type: 'bytes32', indexed: true },
        {
          name: 'previousAdminRole',
          internalType: 'bytes32',
          type: 'bytes32',
          indexed: true,
        },
        {
          name: 'newAdminRole',
          internalType: 'bytes32',
          type: 'bytes32',
          indexed: true,
        },
      ],
      name: 'RoleAdminChanged',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        { name: 'role', internalType: 'bytes32', type: 'bytes32', indexed: true },
        {
          name: 'account',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'sender',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
      ],
      name: 'RoleGranted',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        { name: 'role', internalType: 'bytes32', type: 'bytes32', indexed: true },
        {
          name: 'account',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'sender',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
      ],
      name: 'RoleRevoked',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'controller',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'oldValue',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        {
          name: 'newValue',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'StakeDurationUpdated',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'hodler',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'operator',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'amount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'Staked',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'hodler',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'fingerprint',
          internalType: 'string',
          type: 'string',
          indexed: false,
        },
        {
          name: 'amount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        {
          name: 'operator',
          internalType: 'address',
          type: 'address',
          indexed: false,
        },
      ],
      name: 'Unlocked',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'account',
          internalType: 'address',
          type: 'address',
          indexed: false,
        },
      ],
      name: 'Unpaused',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'hodler',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'operator',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'amount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'Unstaked',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'hodler',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'gasEstimate',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        { name: 'redeem', internalType: 'bool', type: 'bool', indexed: false },
      ],
      name: 'UpdateRewards',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'implementation',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
      ],
      name: 'Upgraded',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'hodler',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'amount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
        {
          name: 'availableAt',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'Vaulted',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'hodler',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'amount',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'Withdrawn',
    },
    {
      type: 'function',
      inputs: [],
      name: 'CONTROLLER_ROLE',
      outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'DEFAULT_ADMIN_ROLE',
      outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'GOVERNANCE_DURATION',
      outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'LOCK_DURATION',
      outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'LOCK_SIZE',
      outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'PAUSER_ROLE',
      outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'STAKE_DURATION',
      outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'UPGRADER_ROLE',
      outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'VERSION',
      outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [{ name: '_amount', internalType: 'uint256', type: 'uint256' }],
      name: 'addVotes',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [],
      name: 'controllerAddress',
      outputs: [{ name: '', internalType: 'address payable', type: 'address' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'emergencyWithdraw',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [],
      name: 'getHodlerKeys',
      outputs: [{ name: '', internalType: 'address[]', type: 'address[]' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [
        { name: '_fingerprint', internalType: 'string', type: 'string' },
        { name: '_operator', internalType: 'address', type: 'address' },
      ],
      name: 'getLock',
      outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [{ name: '_address', internalType: 'address', type: 'address' }],
      name: 'getLocks',
      outputs: [
        {
          name: '',
          internalType: 'struct Hodler.LockData[]',
          type: 'tuple[]',
          components: [
            { name: 'fingerprint', internalType: 'string', type: 'string' },
            { name: 'operator', internalType: 'address', type: 'address' },
            { name: 'amount', internalType: 'uint256', type: 'uint256' },
          ],
        },
      ],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [{ name: 'role', internalType: 'bytes32', type: 'bytes32' }],
      name: 'getRoleAdmin',
      outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [{ name: '_address', internalType: 'address', type: 'address' }],
      name: 'getStake',
      outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [{ name: '_address', internalType: 'address', type: 'address' }],
      name: 'getStakes',
      outputs: [
        {
          name: '',
          internalType: 'struct Hodler.StakeData[]',
          type: 'tuple[]',
          components: [
            { name: 'operator', internalType: 'address', type: 'address' },
            { name: 'amount', internalType: 'uint256', type: 'uint256' },
          ],
        },
      ],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [{ name: '_address', internalType: 'address', type: 'address' }],
      name: 'getVaults',
      outputs: [
        {
          name: '',
          internalType: 'struct Hodler.VaultData[]',
          type: 'tuple[]',
          components: [
            { name: 'amount', internalType: 'uint256', type: 'uint256' },
            { name: 'availableAt', internalType: 'uint256', type: 'uint256' },
            { name: 'kind', internalType: 'uint256', type: 'uint256' },
            { name: 'data', internalType: 'string', type: 'string' },
          ],
        },
      ],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [
        { name: 'role', internalType: 'bytes32', type: 'bytes32' },
        { name: 'account', internalType: 'address', type: 'address' },
      ],
      name: 'grantRole',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        { name: 'role', internalType: 'bytes32', type: 'bytes32' },
        { name: 'account', internalType: 'address', type: 'address' },
      ],
      name: 'hasRole',
      outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
      name: 'hodlerKeys',
      outputs: [{ name: '', internalType: 'address', type: 'address' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [{ name: '', internalType: 'address', type: 'address' }],
      name: 'hodlers',
      outputs: [
        { name: 'available', internalType: 'uint256', type: 'uint256' },
        { name: 'votes', internalType: 'uint256', type: 'uint256' },
        { name: 'gas', internalType: 'uint256', type: 'uint256' },
        { name: 'isSet', internalType: 'bool', type: 'bool' },
        { name: 'claimedRelayRewards', internalType: 'uint256', type: 'uint256' },
        {
          name: 'claimedStakingRewards',
          internalType: 'uint256',
          type: 'uint256',
        },
      ],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [
        { name: '_tokenAddress', internalType: 'address', type: 'address' },
        { name: '_controller', internalType: 'address payable', type: 'address' },
        { name: '_lockSize', internalType: 'uint256', type: 'uint256' },
        { name: '_lockDuration', internalType: 'uint256', type: 'uint256' },
        { name: '_stakeDuration', internalType: 'uint256', type: 'uint256' },
        { name: '_governanceDuration', internalType: 'uint256', type: 'uint256' },
        { name: '_rewardsPoolAddress', internalType: 'address', type: 'address' },
      ],
      name: 'initialize',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        { name: 'fingerprint', internalType: 'string', type: 'string' },
        { name: '_operator', internalType: 'address', type: 'address' },
      ],
      name: 'lock',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [],
      name: 'openExpired',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [],
      name: 'pause',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [],
      name: 'paused',
      outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'proxiableUUID',
      outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'redeem',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [{ name: '_amount', internalType: 'uint256', type: 'uint256' }],
      name: 'removeVotes',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        { name: 'role', internalType: 'bytes32', type: 'bytes32' },
        { name: 'account', internalType: 'address', type: 'address' },
      ],
      name: 'renounceRole',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        { name: 'role', internalType: 'bytes32', type: 'bytes32' },
        { name: 'account', internalType: 'address', type: 'address' },
      ],
      name: 'revokeRole',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        { name: '_address', internalType: 'address', type: 'address' },
        {
          name: '_relayRewardAllocation',
          internalType: 'uint256',
          type: 'uint256',
        },
        {
          name: '_stakingRewardAllocation',
          internalType: 'uint256',
          type: 'uint256',
        },
        { name: '_gasEstimate', internalType: 'uint256', type: 'uint256' },
        { name: '_redeem', internalType: 'bool', type: 'bool' },
      ],
      name: 'reward',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [],
      name: 'rewardsPoolAddress',
      outputs: [{ name: '', internalType: 'address', type: 'address' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [{ name: '_seconds', internalType: 'uint256', type: 'uint256' }],
      name: 'setGovernanceDuration',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [{ name: '_seconds', internalType: 'uint256', type: 'uint256' }],
      name: 'setLockDuration',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [{ name: '_size', internalType: 'uint256', type: 'uint256' }],
      name: 'setLockSize',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [{ name: '_seconds', internalType: 'uint256', type: 'uint256' }],
      name: 'setStakeDuration',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        { name: '_address', internalType: 'address', type: 'address' },
        { name: '_amount', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'stake',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [{ name: 'interfaceId', internalType: 'bytes4', type: 'bytes4' }],
      name: 'supportsInterface',
      outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'tokenContract',
      outputs: [{ name: '', internalType: 'contract IERC20', type: 'address' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [
        { name: 'fingerprint', internalType: 'string', type: 'string' },
        { name: '_operator', internalType: 'address', type: 'address' },
      ],
      name: 'unlock',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [],
      name: 'unpause',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        { name: '_address', internalType: 'address', type: 'address' },
        { name: '_amount', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'unstake',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        { name: 'newImplementation', internalType: 'address', type: 'address' },
      ],
      name: 'upgradeTo',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        { name: 'newImplementation', internalType: 'address', type: 'address' },
        { name: 'data', internalType: 'bytes', type: 'bytes' },
      ],
      name: 'upgradeToAndCall',
      outputs: [],
      stateMutability: 'payable',
    },
    {
      type: 'function',
      inputs: [],
      name: 'version',
      outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
      stateMutability: 'pure',
    },
    {
      type: 'function',
      inputs: [{ name: '_amount', internalType: 'uint256', type: 'uint256' }],
      name: 'withdraw',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    { type: 'receive', stateMutability: 'payable' },
  ] as const